trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: |
      curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      wasm-pack build
    workingDirectory: '$(Build.SourcesDirectory)\wasm'  
  displayName: 'Install wasm-pack and build Rust'

- task: CmdLine@2
  inputs:
    script: 'npm install'
  displayName: 'npm install'
  
- task: CmdLine@2
  inputs:
    script: 'npm run build'
  displayName: 'npm run build'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)\dist\rust-wasm-angular\*'
    azureSubscription: 'Azure subscription 1(e1d33e78-07f6-4df4-b39d-979bad805079)'
    Destination: 'AzureBlob'
    storage: 'rustwasmangular'
    ContainerName: '$web'
  displayName: 'Copy files to Azure'